package com.coinly.backend.model

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.math.BigDecimal

@Entity
@Table(name = "coins")
class Coin(

    @Id
    //Primary key managed externally (UUID generated by Flutter client)
    val id: String,

    @Column(nullable = false)
    val name: String,

    @Column(nullable = false)
    val country: String,

    @Column(name = "face_value", nullable = false)
    val faceValue: BigDecimal,

    @Column(nullable = true)
    val year: Int? = null,

    //Stores associated image filename in persistent storage
    @Column(name = "image_url", nullable = true)
    var imageUrl: String? = null
)