spring.application.name=backend

# ==========================================
# DATABASE CONFIGURATION (POSTGRESQL)
# ==========================================
# Spring Boot will automatically inject the values of the environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# HIBERNATE / JPA CONFIGURATIONS
# ==========================================
# Tells Hibernate to use the PostgreSQL language
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' automatically updates tables when we change the Kotlin code
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL being executed in the terminal (debug)
spring.jpa.show-sql=true